name: Build Armbian for QEMU aarch64

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static qemu-utils binfmt-support

      - name: Clone Armbian Build
        run: |
          git clone https://github.com/armbian/build.git
          cd build

      - name: Build Armbian Image
        run: |
          cd build
          ./compile.sh BOARD=qemu-uboot-arm64 BRANCH=current RELEASE=bookworm BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no COMPILE_KERNEL=yes CLEAN_LEVEL=make-clean PROGRESS_DISPLAY=none LOG_VERBOSE=ye


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: build/output/images/*
