name: Build Armbian Kernel for QEMU aarch64


on:
  workflow_dispatch:

  push:
    tags:
      - 'v*-build' # Сработает при git push origin v1.2.3-build


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static qemu-utils binfmt-support

      - name: Clone Armbian Build
        run: |
          git clone https://github.com/armbian/build.git
          cd build

      - name: Build Armbian Image
        run: |
          cd build
          ./compile.sh kernel \
          BOARD=qemu-uboot-arm64 \
          BRANCH=current \
          RELEASE=trixie \
          KERNEL_CONFIGURE=no \
          COMPILE_KERNEL=no \
          LOG_VERBOSE=yes

#         ls -lR ./output/
#          #
#          #          BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no COMPILE_KERNEL=yes CLEAN_LEVEL=make-clean PROGRESS_DISPLAY=none LOG_VERBOSE=ye
#          ./compile.sh kernel \
###          BOARD=qemu-uboot-arm64 \
#          BRANCH=current \
#          RELEASE=trixie \
#          USE_CACHE=no \
#          LOCAL_CACHE=no \
#          CLEAN_LEVEL=distclean \
#          LOG_VERBOSE=yes
##

#          ls -lR ./output/

#     - name: Compile Kernel (ignore cache)
#       run: |
#         cd build
#         ./compile.sh kernel \
#           BOARD=qemu-uboot-arm64 \
#           BRANCH=current \
#           RELEASE=trixie \
#           ARTIFACT_IGNORE_CACHE=yes \
#           CLEAN_LEVEL=distclean

#         ls -lR ./output/


#     - name: Extract vmlinuz and DTB
#       run: |
#         cd build/output/
#         mkdir ./debs/extracted
#         dpkg-deb -x ./debs/linux-image-*.deb ./debs/extracted/
#         dpkg-deb -x ./debs/linux-dtb-*.deb ./debs/extracted/

#     - name: Extract initrd from deb package
#       run: |
#         cd build
#         mkdir tmp_deb_extract
#         dpkg-deb -x output/debs/linux-image-*.deb tmp_deb_extract/
#         KERNEL_VER=$(dpkg-deb -f output/debs/linux-image-*.deb Armbian-Kernel-Version)

#         if [ -z "$KERNEL_VER" ]; then
#         echo "Error: Armbian-Kernel-Version not found in deb package!"
#         exit 1
#         fi
#         echo "Detected kernel version: $KERNEL_VER"


#         MODULES_DIR=tmp_deb_extract/lib/modules/$KERNEL_VER \
#           sudo mkinitramfs -o output/images/initrd.img-$KERNEL_VER $KERNEL_VER
#         lsinitramfs output/debs/extracted/boot/initrd.img-$KERNEL_VER | grep virtio_blk
#         rm -rf tmp_deb_extract


#     - name: Pack vmlinuz, DTB and initrd
#       run: |
#         cd build/output/
#         KERNEL_VER=$(dpkg-deb -f output/debs/linux-image-*.deb Armbian-Kernel-Version)

#         if [ -z "$KERNEL_VER" ]; then
#         echo "Error: Armbian-Kernel-Version not found in deb package!"
#         exit 1
#         fi
#         echo "Detected kernel version: $KERNEL_VER"

#         cd ./debs/extracted/boot/
#         tar cvf $GITHUB_WORKSPACE/build/output/images/linux-image-$KERNEL_VER.tar.gz *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian_kernel
          path: |
            build/output/images/vmlinuz-*
            build/output/images/dtb-*/*.dtb
            build/output/images/modules-*.tgz
            build/output/debs/*.deb
            #
            #build/output/images/linux-image.tar.gz

            if-no-files-found: error
