name: Build Armbian Kernel for QEMU aarch64


on:
  workflow_dispatch:

  push:
    tags:
      - 'v*-build' # Сработает при git push origin v1.2.3-build


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static qemu-utils binfmt-support

      - name: Clone Armbian Build
        run: |
          git clone https://github.com/armbian/build.git
          cd build

      - name: Build Armbian Image
        run: |
          cd build
          #./compile.sh kernel \
          #BOARD=qemu-uboot-arm64 \
          #BRANCH=current \
          #RELEASE=bookworm \
          #LOG_VERBOSE=yes \
          #COMPILE_KERNEL=yes
          #
          #          BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no COMPILE_KERNEL=yes CLEAN_LEVEL=make-clean PROGRESS_DISPLAY=none LOG_VERBOSE=ye
          ./compile.sh kernel \
          BOARD=qemu-uboot-arm64 \
          BRANCH=current \
          RELEASE=trixie \
          USE_CACHE=no \
          LOCAL_CACHE=no \
          CLEAN_LEVEL=distclean \
          LOG_VERBOSE=yes

          ls -lR ./output/


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-kernel
          path: |
            build/output/images/vmlinuz-*
            build/output/images/dtb-*/*.dtb
            build/output/images/modules-*.tgz
            if-no-files-found: error
